version: "3"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 3000:3000

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/javascript/frontend
    ports:
      - 3001:3001
