apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-service
  type: LoadBalancer
  ports:
    - name: backend-service
      port: 3000
      targetPort: 3000
      protocol: TCP
